services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cargopulse/app
    container_name: cargopulse_app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www

  postgres:
    image: postgres:15
    container_name: cargopulse_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cargopulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cargopulse_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: